<a href="https://colab.research.google.com/github/dongzooo/Data-Analysis/blob/main/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D(linear_regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 필요한 라이브러리 import 

import numpy as np # 데이터를 임의로 만들어내는데 필요 
from sklearn.linear_model import LinearRegression


In [ ]:
# 실험용으로 데이터 만들기
# single independant variable x, output: y
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1,1))
y = np.array([5, 20, 14, 32, 33, 38])

In [ ]:
x 

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [ ]:
model = LinearRegression()
# default option으로 model을 만듬
# 여기의 model은 빈 모델 


In [ ]:
# x, y
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_sq = model.score(x, y)
print('coeffient of determination: ', r_sq)

coeffient of determination:  0.8614075972966675


In [ ]:
print('intercept: ', model.intercept_)
print('coeffient of determination: ', model.coef_)

# y = 0.6343x + 4.6381


intercept:  4.638095238095236
coeffient of determination:  [0.63428571]


In [ ]:
y_pred = model.predict(x)
print(y_pred)

[ 7.80952381 14.15238095 20.4952381  26.83809524 33.18095238 39.52380952]


In [ ]:

# predicted: [ 7.80952381 14.15238095 20.4952381  26.83809524 33.18095238 39.52380952]
# provided: [5, 20, 14, 32, 33, 38]


In [ ]:
x_new = np.arange(5).reshape((-1,1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
print(y)

[ 5 20 14 32 33 38]


In [ ]:
y_new = model.predict(x_new)
print(y_new)

[4.63809524 5.27238095 5.90666667 6.54095238 7.1752381 ]


In [ ]:
# 다중회귀
# x를 2 dimensional (2D) array로 만든다 
x = [[0, 1],[5, 1],[15, 2],[25, 5],[35, 11],[45, 15],[55, 34],[60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]


In [ ]:
x = np.array(x)
y = np.array(y)
# x, y = np.array(x), np.array(y)

In [ ]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [ ]:
# model = LinearRegression()
# model.fit(x, y)
model = LinearRegression().fit(x, y)

In [ ]:
r_sq = model.score(x, y)
intercept = model.intercept_
coefficient = model.coef_

print('r sqaure: ', r_sq)
print('intercept: ', intercept)
print('coefficient: ', coefficient)

r sqaure:  0.8615939258756776
intercept:  5.52257927519819
coefficient:  [0.44706965 0.25502548]


In [ ]:
y_pred = model.predict(x)
print(y_pred)

[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [ ]:
# [ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957 38.78227633 41.27265006]
# [4, 5, 20, 14, 32, 22, 38, 43]
x_new = [[1, 15], [3,28], [25, 34]]
x_new = np.array(x_new)

In [ ]:
x_new

array([[ 1, 15],
       [ 3, 28],
       [25, 34]])

In [ ]:
y_pred = model.predict(x_new)
print(y_pred)

[ 9.79503114 14.0045017  25.37018686]
